# Generated by Django 5.1.3 on 2024-11-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gebruikersAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(default="Netherlands", max_length=100),
        ),
    ]
