# Generated by Django 5.1.3 on 2024-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikersAPI', '0003_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Undefined', max_length=100),
        ),
    ]
