# Generated by Django 5.1.3 on 2024-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gebruikersAPI", "0004_alter_user_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
