# Generated by Django 5.1.3 on 2024-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikersAPI', '0008_alter_artist_artistid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artistID',
        ),
        migrations.AddField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
