# Generated by Django 5.1.3 on 2024-12-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikersAPI', '0010_artists_delete_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artistID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
