# Generated by Django 5.1.3 on 2024-12-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikersAPI', '0011_alter_artists_artistid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='artistID',
            new_name='artistsID',
        ),
    ]
