# Generated by Django 5.1.3 on 2024-12-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikersAPI', '0014_remove_artists_artistsid_artists_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
