# Generated by Django 5.1.3 on 2024-12-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikersAPI', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
