# Generated by Django 5.1.3 on 2024-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gebruikersAPI", "0017_delete_artists"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artists",
            fields=[
                ("artistID", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
    ]
