# Generated by Django 5.1.3 on 2024-12-01 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gebruikersAPI", "0018_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Artists",
            new_name="Artist",
        ),
    ]
