# Generated by Django 5.1.3 on 2024-12-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebruikersAPI', '0021_album_artist_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_full_name',
        ),
    ]
