# Generated by Django 5.1.3 on 2024-12-02 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gebruikersAPI", "0023_genre_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="genreID",
            field=models.ForeignKey(
                default="Not Defined yet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gebruikersAPI.genre",
            ),
        ),
    ]
